- job:
    name: monascaevents-tempest-events-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/monasca-tempest-events-base/run.yaml
    post-run: playbooks/legacy/monasca-tempest-events-base/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/monasca-events-api
      - openstack/monasca-common
      - openstack/monasca-persister
      - openstack/python-monascaclient
      - openstack/tempest
    voting: false

- project:
    templates:
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - monascaevents-tempest-events-base
    gate:
      queue: monasca
